.TH CPABE-UPDATEPK "1" "August 2020" "SRI International" "User Commands"
.SH NAME
cpabe-updatepk \- manual page for cpabe-updatepk 0.1
.SH SYNOPSIS
.B cpabe-updatepk
[\fIOPTION \fR...] \fIPUB_KEY UPD_KEY \fR
.SH DESCRIPTION
Update the public key PUB_KEY using the update key UPD_KEY up to UPD_KEY's version.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.TP
\fB\-d\fR, \fB\-\-deterministic\fR
use deterministic "random" numbers
(only for debugging)
.PP
Parts Copyright (C) 2006, 2007 John Bethencourt and SRI International.
This is free software released under the GPL, see the source for copying
conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
.SH EXAMPLES

Update the public key:

  $ cpabe-updatepk pub_key upd_key

.SH "REPORTING BUGS"
Report bugs to ???
.SH "SEE ALSO"
.BR cpabe-setup (1),
.BR cpabe-enc (1),
.BR cpabe-keygen (1),
.BR cpabe-dec (1),
.BR cpabe-updatemk (1),
.BR cpabe-updatedk (1),
.BR cpabe-updatecp (1)
