.TH SEABREW-ABE-UPDATE-PK "1" "January 2021" "SRI International" "User Commands"
.SH NAME
seabrew-abe-update-pk \- manual page for seabrew-abe-update-pk 0.1
.SH SYNOPSIS
.B seabrew-abe-update-pk
[\fIOPTION \fR...] \fI PUB_KEY MSK_KEY UPD_KEY \fR
.SH DESCRIPTION
Substitute the h field containted in the public key PUB_KEY
with that contained in U_PK, thus updating PUB_KEY.
.PP
The new public key is updated up to the version contained in U_PK.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.TP
\fB\-d\fR, \fB\-\-deterministic\fR
use deterministic "random" numbers
(only for debugging)
.SH EXAMPLES

Update the public key pub_key using the h field contained in u_pk:

  $ seabrew-abe-update-dk pub_key u_pk

.SH "REPORTING BUGS"
Report bugs to University of Pisa.
.SH "SEE ALSO"
.BR seabrew-abe-setup (1),
.BR seabrew-abe-keygen (1),
.BR seabrew-abe-dec (1),
.BR seabrew-abe-enc (1),
.BR seabrew-abe-update-mk (1),
.BR seabrew-abe-update-dk (1),
.BR seabrew-abe-update-cp (1),
.BR seabrew-abe-extract (1),
.BR seabrew-abe-extract-d (1),
.BR seabrew-abe-extract-u-pk (1),
.BR seabrew-abe-print-msk (1),
.BR seabrew-abe-print-pub (1),
.BR seabrew-abe-print-cph (1),
.BR seabrew-abe-print-prv (1),
.BR seabrew-abe-print-upd (1)
