.TH SEABREW-ABE-UPDATE-D "1" "January 2021" "SRI International" "User Commands"
.SH NAME
seabrew-abe-update-d \- manual page for seabrew-abe-update-d 0.1
.SH SYNOPSIS
.B seabrew-abe-update-d
[\fIOPTION \fR...] \fI D_FILE UPD_KEY PUB_KEY \fR
.SH DESCRIPTION
Update the D field contained in D_FILE using the update key(s) UPD_KEY
and the public key PUB_KEY.
.PP
The new D field is updated up to UPD_KEY's latest version.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.TP
\fB\-d\fR, \fB\-\-deterministic\fR
use deterministic "random" numbers
(only for debugging)
.SH EXAMPLES

Update the D field contained in prv_key.d up to the latest upd_key's version:

  $ seabrew-abe-update-d prv_key.d upd_key pub_key

.SH "REPORTING BUGS"
Report bugs to University of Pisa.
.SH "SEE ALSO"
.BR seabrew-abe-setup (1),
.BR seabrew-abe-keygen (1),
.BR seabrew-abe-dec (1),
.BR seabrew-abe-enc (1),
.BR seabrew-abe-update-mk (1),
.BR seabrew-abe-update-dk (1),
.BR seabrew-abe-update-pk (1),
.BR seabrew-abe-updated-cp (1),
.BR seabrew-abe-extract-u-pk (1),
.BR seabrew-abe-extract (1),
.BR seabrew-abe-print-msk (1),
.BR seabrew-abe-print-pub (1),
.BR seabrew-abe-print-cph (1),
.BR seabrew-abe-print-prv (1),
.BR seabrew-abe-print-upd (1)
