.TH SEABREW-ABE-UPDATEDK "1" "November 2020" "SRI International" "User Commands"
.SH NAME
seabrew-abe-update-partial-updates \- manual page for seabrew-abe-update-partial-updates 0.1
.SH SYNOPSIS
.B seabrew-abe-update-partial-updates
[\fIOPTION \fR...] \fIPARTIAL_UPDATES UPD_KEY PUB_KEY \fR
.SH DESCRIPTION
Using the updated public (encryption) key PUB_KEY and the quantities carried by UPD_KEY, update the partial updates carried by PARTIAL_UPDATES.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.SH EXAMPLES

Update the "partial_updates" using "upd_key" and "pub_key":

  $ seabrew-abe-update-partial-updates partial_updates upd_key pub_key

.SH "REPORTING BUGS"
Report bugs to University of Pisa.
.SH "SEE ALSO"
.BR seabrew-abe-setup (1),
.BR seabrew-abe-keygen (1),
.BR seabrew-abe-enc (1),
.BR seabrew-abe-dec (1),
.BR seabrew-abe-updatemk (1),
.BR seabrew-abe-updatecp (1),
.BR seabrew-abe-update-pub-and-prv-partial (1)
