.TH SEABREW-ABE-UPDATECP "1" "November 2020" "SRI International" "User Commands"
.SH NAME
seabrew-abe-updatecp \- manual page for seabrew-abe-updatecp 0.1
.SH SYNOPSIS
.B seabrew-abe-updatecp
[\fIOPTION \fR...] \fICPH UPD_KEY PUB_KEY \fR
.SH DESCRIPTION
Blindly update the cipher-text CPH using the update key UPD_KEY and public key PUB_KEY parameters.
.PP
The new ciphertext is updated up UPD_KEY's verion.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.TP
\fB\-d\fR, \fB\-\-deterministic\fR
use deterministic "random" numbers
(only for debugging)
.SH EXAMPLES

Update the cipher-text "document.txt.cpabe"

  $ seabrew-abe-updatecp document.txt.cpabe upd_key pub_key

.SH "REPORTING BUGS"
Report bugs to University of Pisa.
.SH "SEE ALSO"
.BR seabrew-abe-setup (1),
.BR seabrew-abe-keygen (1),
.BR seabrew-abe-enc (1),
.BR seabrew-abe-dec (1),
.BR seabrew-abe-updatemk (1),
.BR seabrew-abe-update-partial-updates (1),
.BR seabrew-abe-update-pub-and-prv-partial (1)
