.TH CPABE-UPDATEDK "1" "September 2020" "SRI International" "User Commands"
.SH NAME
cpabe-update-partial-updates \- manual page for cpabe-update-partial-updates 0.1
.SH SYNOPSIS
.B cpabe-update-partial-updates
[\fIOPTION \fR...] \fIPARTIAL_UPDATES UPD_KEY PUB_KEY \fR
.SH DESCRIPTION
Using the updated public (encryption) key PUB_KEY and the quantities carried by UPD_KEY, update the partial updates carried by PARTIAL_UPDATES.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.PP
Parts Copyright (C) 2006, 2007 John Bethencourt and SRI International.
This is free software released under the GPL, see the source for copying
conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
.SH EXAMPLES

Update the "partial_updates" using "upd_key" and "pub_key":

  $ cpabe-update-partial-updates partial_updates upd_key pub_key

.SH "REPORTING BUGS"
Report bugs to ???
.SH "SEE ALSO"
.BR cpabe-setup (1),
.BR cpabe-enc (1),
.BR cpabe-keygen (1),
.BR cpabe-dec (1),
.BR cpabe-updatemk (1),
.BR cpabe-updatepk (1),
.BR cpabe-updatecp (1),
.BR cpabe-update-pub-and-prv-partial (1),
.BR cpabe-print (1)
